### ISSUE TITLE
How to run on Linux (solved)

### ISSUE THREAD

**Issue by kwautztretschke** [mungewell/zoom-zt2#25]
Disclaimer: I'm a noob.
Since the prebuilt .exe doesn't do anything except open a blank commandline (which does appear to block some Midi ports or something, but no gui), I've tried running the script on Linux.
First of all, there were three python modules I installed with pip (construct, mido, rtmidi), but now it just returns more obscure errors.
Do I need more modules? Am I running the .exe wrong?

```
$ python3 zoomzt2-gui.py 
Traceback (most recent call last):
  File "/mnt/data/Downloads/B1Xon_v1.30_Win_E/zoom-zt2-prebuilt-0.4.0/zoomzt2-gui.py", line 289, in OnInit
    self.frame = _479389042__675845753_MyFrame(None, wx.ID_ANY, "")
  File "/mnt/data/Downloads/B1Xon_v1.30_Win_E/zoom-zt2-prebuilt-0.4.0/zoomzt2-gui.py", line 57, in __init__
    if self.ConnectPedal():
  File "/mnt/data/Downloads/B1Xon_v1.30_Win_E/zoom-zt2-prebuilt-0.4.0/zoomzt2-gui.py", line 246, in ConnectPedal
    if self.pedal.connect():
  File "/mnt/data/Downloads/B1Xon_v1.30_Win_E/zoom-zt2-prebuilt-0.4.0/zoomzt2.py", line 115, in connect
    for port in mido.get_input_names():
  File "/home/bernie/.local/lib/python3.9/site-packages/mido/backends/backend.py", line 169, in get_input_names
    devices = self._get_devices(**self._add_api(kwargs))
  File "/home/bernie/.local/lib/python3.9/site-packages/mido/backends/backend.py", line 163, in _get_devices
    return self.module.get_devices(**self._add_api(kwargs))
  File "/home/bernie/.local/lib/python3.9/site-packages/mido/backends/rtmidi.py", line 50, in get_devices
    rtapi = _get_api_id(api)
  File "/home/bernie/.local/lib/python3.9/site-packages/mido/backends/rtmidi.py", line 34, in _get_api_id
    return rtmidi.API_UNSPECIFIED
AttributeError: module 'rtmidi' has no attribute 'API_UNSPECIFIED'
OnInit returned false, exiting...
```

**Comment by kwautztretschke** [comment]
okay progress:
rtmidi is the wrong package, I needed python3-rtmidi, which I installed via apt, instead of pip.
This does not produce errors when starting zoomzt2-gui.py, but instead just does nothing.
No gui is shown.

**Comment by kwautztretschke** [comment]
More progress:
you need the wx-common apt package.
The program just fails silently and does nothing when the package is absent, instead of producing any meaningful error.
Had to find that out by painfully scraping through code.
Now it shows a gui and appears to connect to the effectpedal.
