### ISSUE TITLE
Can not install 'RHYTHM_100' - subcon build 14 bytes but was allowed only 12

### ISSUE THREAD

**Issue by mungewell** [mungewell/zoom-zt2#43]
Attempting to install "RHYTHM_100" from GCE-3 on a G1Four.

```
simon@thevoid:~/zoom-zt2-sdw-github/zoom_fx/GCE-3/GL$ python3 ../../../zoomzt2.py -I  RHYTHM_100.zd2 
Installing effect: RHYTHM_100.zd2
Traceback (most recent call last):
  File "../../../zoomzt2.py", line 757, in <module>
    main()
  File "../../../zoomzt2.py", line 706, in main
    data = pedal.add_effect_from_filename(data, target)
  File "../../../zoomzt2.py", line 306, in add_effect_from_filename
    return self.add_effect(data, tail, binconfig['version'], binconfig['id'])
  File "../../../zoomzt2.py", line 295, in add_effect
    return ZT2.build(config)
  File "/usr/local/lib/python3.6/dist-packages/construct-2.10.67-py3.6.egg/construct/core.py", line 336, in build
  File "/usr/local/lib/python3.6/dist-packages/construct-2.10.67-py3.6.egg/construct/core.py", line 348, in build_stream
  File "/usr/local/lib/python3.6/dist-packages/construct-2.10.67-py3.6.egg/construct/core.py", line 4109, in _build
  File "/usr/local/lib/python3.6/dist-packages/construct-2.10.67-py3.6.egg/construct/core.py", line 2296, in _build
  File "/usr/local/lib/python3.6/dist-packages/construct-2.10.67-py3.6.egg/construct/core.py", line 2657, in _build
  File "/usr/local/lib/python3.6/dist-packages/construct-2.10.67-py3.6.egg/construct/core.py", line 2503, in _build
  File "/usr/local/lib/python3.6/dist-packages/construct-2.10.67-py3.6.egg/construct/core.py", line 2144, in _build
  File "/usr/local/lib/python3.6/dist-packages/construct-2.10.67-py3.6.egg/construct/core.py", line 2657, in _build
  File "/usr/local/lib/python3.6/dist-packages/construct-2.10.67-py3.6.egg/construct/core.py", line 2503, in _build
  File "/usr/local/lib/python3.6/dist-packages/construct-2.10.67-py3.6.egg/construct/core.py", line 2144, in _build
  File "/usr/local/lib/python3.6/dist-packages/construct-2.10.67-py3.6.egg/construct/core.py", line 2657, in _build
  File "/usr/local/lib/python3.6/dist-packages/construct-2.10.67-py3.6.egg/construct/core.py", line 708, in _build
  File "/usr/local/lib/python3.6/dist-packages/construct-2.10.67-py3.6.egg/construct/core.py", line 4848, in _build
construct.core.PaddingError: Error in path (building) -> groups -> effects -> effect
subcon build 14 bytes but was allowed only 12
```

**Comment by mungewell** [comment]
```
$ echo -n 'RHYTHM_100.zd2' | wc
      0       1      14
```
