### ISSUE TITLE
MS-60B+ effect decode glitch

### ISSUE THREAD

**Issue by mungewell** [mungewell/zoom-zt2#79]
`decode_effect.py` glitches on a few of the installed effects, seems related to characters in name.
```
Traceback (most recent call last):
  File "/home/simon/zoom-zt2-sdw-github/zoom_fx_ms-plus/ms-60b/../../decode_effect.py", line 244, in <module>
    main()
  File "/home/simon/zoom-zt2-sdw-github/zoom_fx_ms-plus/ms-60b/../../decode_effect.py", line 121, in main
    config = zoomzt2.ZD2.parse(data)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/construct-2.10.70-py3.11.egg/construct/core.py", line 404, in parse
  File "/usr/local/lib/python3.11/dist-packages/construct-2.10.70-py3.11.egg/construct/core.py", line 416, in parse_stream
  File "/usr/local/lib/python3.11/dist-packages/construct-2.10.70-py3.11.egg/construct/core.py", line 428, in _parsereport
  File "/usr/local/lib/python3.11/dist-packages/construct-2.10.70-py3.11.egg/construct/core.py", line 2236, in _parse
  File "/usr/local/lib/python3.11/dist-packages/construct-2.10.70-py3.11.egg/construct/core.py", line 428, in _parsereport
  File "/usr/local/lib/python3.11/dist-packages/construct-2.10.70-py3.11.egg/construct/core.py", line 2770, in _parse
  File "/usr/local/lib/python3.11/dist-packages/construct-2.10.70-py3.11.egg/construct/core.py", line 428, in _parsereport
  File "/usr/local/lib/python3.11/dist-packages/construct-2.10.70-py3.11.egg/construct/core.py", line 820, in _parse
  File "/usr/local/lib/python3.11/dist-packages/construct-2.10.70-py3.11.egg/construct/core.py", line 1721, in _decode
construct.core.StringError: cannot use encoding 'ascii' to decode b'PITCH SHIFT\xff\xe5'
```

The other effects decode as:
[effects_sort.txt](https://github.com/user-attachments/files/16829852/effects_sort.txt)

**Comment by mungewell** [comment]
This is the same problem as #76 

Affects these effects
```
-rw-rw-r-- 1 simon simon     0 Sep  6 20:40 B_MOCT.ZD2.txt
-rw-rw-r-- 1 simon simon     0 Sep  6 20:40 B_OCTAVE.ZD2.txt
-rw-rw-r-- 1 simon simon     0 Sep  6 20:40 B_PITCH.ZD2.txt
-rw-rw-r-- 1 simon simon     0 Sep  6 20:40 B_PLY_LT.ZD2.txt
-rw-rw-r-- 1 simon simon     0 Sep  6 20:40 B_PLYOCT.ZD2.txt
-rw-rw-r-- 1 simon simon     0 Sep  6 20:40 HPS.ZD2.txt
```

**Comment by mungewell** [comment]
This is due to the long GroupName for 'PITCH_SHIFT', 11 characters.
```
00000050  00 00 00 00 00 00 00 00  01 31 2e 31 30 00 00 07  |.........1.10...|
00000060  50 00 00 07 48 50 53 00  00 00 00 00 27 b6 3e 50  |P...HPS.....'.>P|
00000070  49 54 43 48 20 53 48 49  46 54 ff e5 00 00 00 00  |ITCH SHIFT......|
                                         ^^ ^^
00000080  49 43 4f 4e b6 00 00 00  42 4d b6 00 00 00 00 00  |ICON....BM......|
00000090  00 00 3e 00 00 00 28 00  00 00 17 00 00 00 1e 00  |..>...(.........|
```

Fixed.

**Comment by mungewell** [comment]
Crap, broke other stuff... working on it. :-0

**Comment by mungewell** [comment]
Hopefully fixed now.
